version: '2'
services:
    girosdelsurjhipster-app:
        image: girosdelsurjhipster
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://girosdelsurjhipster-mysql:3306/girosdelsurjhipster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    girosdelsurjhipster-mysql:
        extends:
            file: mysql.yml
            service: girosdelsurjhipster-mysql
